// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbyK1VBauhxRCpCjQwkE514lA-RG4Ap94',
    appId: '1:975324111615:web:f93a4c767e82849bbba2ca',
    messagingSenderId: '975324111615',
    projectId: 'busapp-a7756',
    authDomain: 'busapp-a7756.firebaseapp.com',
    storageBucket: 'busapp-a7756.firebasestorage.app',
    measurementId: 'G-NMXYZEXP12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIU1kBqGfQ8aSuJygD3F_PN26KyiHSG0',
    appId: '1:975324111615:android:aa0ea22829036007bba2ca',
    messagingSenderId: '975324111615',
    projectId: 'busapp-a7756',
    storageBucket: 'busapp-a7756.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9vIZI3qOSAZ6sPvY0XQcwVyvN66rc2A',
    appId: '1:975324111615:ios:feb04f957420f3c4bba2ca',
    messagingSenderId: '975324111615',
    projectId: 'busapp-a7756',
    storageBucket: 'busapp-a7756.firebasestorage.app',
    iosBundleId: 'com.example.busApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb9vIZI3qOSAZ6sPvY0XQcwVyvN66rc2A',
    appId: '1:975324111615:ios:feb04f957420f3c4bba2ca',
    messagingSenderId: '975324111615',
    projectId: 'busapp-a7756',
    storageBucket: 'busapp-a7756.firebasestorage.app',
    iosBundleId: 'com.example.busApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbyK1VBauhxRCpCjQwkE514lA-RG4Ap94',
    appId: '1:975324111615:web:4cfc9eb8b8e65681bba2ca',
    messagingSenderId: '975324111615',
    projectId: 'busapp-a7756',
    authDomain: 'busapp-a7756.firebaseapp.com',
    storageBucket: 'busapp-a7756.firebasestorage.app',
    measurementId: 'G-HRLB05FYH9',
  );
}
